
WNDCLASSA struc	; (sizeof=0x28,	standard type) ; XREF: ...
style dd ?
lpfnWndProc dd ?	; offset
cbClsExtra dd ?
cbWndExtra dd ?
hInstance dd ?		; offset
hIcon dd ?		; offset
hCursor	dd ?		; offset
hbrBackground dd ?	; offset
lpszMenuName dd	?	; offset
lpszClassName dd ?	; offset
WNDCLASSA ends


_SECURITY_ATTRIBUTES struc ; (sizeof=0xC, standard type) ; XREF: ...
nLength	dd ?
lpSecurityDescriptor dd	? ; offset
bInheritHandle dd ?
_SECURITY_ATTRIBUTES ends


_STARTUPINFOA struc ; (sizeof=0x44, standard type) ; XREF: ...
cb dd ?
lpReserved dd ?		; offset
lpDesktop dd ?		; offset
lpTitle	dd ?		; offset
dwX dd ?
dwY dd ?
dwXSize	dd ?
dwYSize	dd ?
dwXCountChars dd ?
dwYCountChars dd ?
dwFillAttribute	dd ?
dwFlags	dd ?
wShowWindow dw ?
cbReserved2 dw ?
lpReserved2 dd ?	; offset
hStdInput dd ?		; offset
hStdOutput dd ?		; offset
hStdError dd ?		; offset
_STARTUPINFOA ends


_PROCESS_INFORMATION struc ; (sizeof=0x10, standard type) ; XREF: ...
hProcess dd ?		; offset
hThread	dd ?		; offset
dwProcessId dd ?
dwThreadId dd ?
_PROCESS_INFORMATION ends


MSG struc ; (sizeof=0x1C, standard type) ; XREF: ...
hwnd dd	?		; offset
message	dd ?
wParam dd ?
lParam dd ?
time dd	?
pt POINT ?
MSG ends


POINT struc ; (sizeof=0x8, standard type) ; XREF: ...
x dd ?
y dd ?
POINT ends


_FILETIME struc	; (sizeof=0x8, standard	type) ;	XREF: ...
dwLowDateTime dd ?
dwHighDateTime dd ?
_FILETIME ends


LARGE_INTEGER union ; (sizeof=0x8, standard type) ; XREF: ...
s _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E ?
u _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E ?
QuadPart dq ?
LARGE_INTEGER ends


_LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E struc	; (sizeof=0x8, standard	type) ;	XREF: ...
LowPart	dd ?
HighPart dd ?
_LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E ends


_SCOPETABLE_ENTRY struc	; (sizeof=0xC) ; XREF: ...
EnclosingLevel dd ?
FilterFunc dd ?		; offset
HandlerFunc dd ?	; offset
_SCOPETABLE_ENTRY ends


CPPEH_RECORD struc ; (sizeof=0x18) ; XREF: ...
old_esp	dd ?		; XREF:	...
exc_ptr	dd ?		; offset
registration _EH3_EXCEPTION_REGISTRATION ? ; XREF: ...
CPPEH_RECORD ends


_EH3_EXCEPTION_REGISTRATION struc ; (sizeof=0x10, standard type) ; XREF: ...
Next dd	?		; offset
ExceptionHandler dd ?	; offset
ScopeTable dd ?		; offset
TryLevel dd ?		; XREF:	...
_EH3_EXCEPTION_REGISTRATION ends


_OSVERSIONINFOA	struc ;	(sizeof=0x94, standard type) ; XREF: ...
dwOSVersionInfoSize dd ?
dwMajorVersion dd ?
dwMinorVersion dd ?
dwBuildNumber dd ?
dwPlatformId dd	?
szCSDVersion db	128 dup(?)
_OSVERSIONINFOA	ends


;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	      Copyright	(c) 2013 Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-3215-7394-8A			    |
; |  Universitaet Bonn/	Institut fuer Informatik Abteilung fuer	Informati   |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	E7484514C0464642BE7B4DC2689354C8
; Input	CRC32 :	87CA8502

; File Name   :	Y:\binaries\IEXPLORE.EXE
; Format      :	Portable executable for	80386 (PE)
; Imagebase   :	400000
; Section 1. (virtual address 00001000)
; Virtual size			: 00001D9B (   7579.)
; Section size in file		: 00001E00 (   7680.)
; Offset to raw	data for section: 00000400
; Flags	60000020: Text Executable Readable
; Alignment	: default
;
; Imports from KERNEL32.dll
;

include	uni.inc	; see unicode subdir of	ida for	info on	unicode

.686p
.mmx
.model flat


; Segment type:	Externs
; _idata
; LONG __stdcall UnhandledExceptionFilter(struct _EXCEPTION_POINTERS *ExceptionInfo)
extrn UnhandledExceptionFilter:dword
; LPSTR	__stdcall GetCommandLineA()
extrn GetCommandLineA:dword
; int __stdcall	lstrlenW(LPCWSTR lpString)
extrn lstrlenW:dword
; int __stdcall	MultiByteToWideChar(UINT CodePage, DWORD dwFlags, LPCSTR lpMultiByteStr, int cbMultiByte, LPWSTR lpWideCharStr,	int cchWideChar)
extrn MultiByteToWideChar:dword
; HANDLE __stdcall CreateEventA(LPSECURITY_ATTRIBUTES lpEventAttributes, BOOL bManualReset, BOOL bInitialState,	LPCSTR lpName)
extrn CreateEventA:dword
; DWORD	__stdcall GetCurrentThreadId()
extrn GetCurrentThreadId:dword
; LPSTR	__stdcall lstrcatA(LPSTR lpString1, LPCSTR lpString2)
extrn lstrcatA:dword
; int __stdcall	lstrlenA(LPCSTR	lpString)
extrn lstrlenA:dword
; int __stdcall	lstrcmpiA(LPCSTR lpString1, LPCSTR lpString2)
extrn lstrcmpiA:dword
; LPSTR	__stdcall lstrcpyA(LPSTR lpString1, LPCSTR lpString2)
extrn lstrcpyA:dword
; DWORD	__stdcall GetModuleFileNameA(HMODULE hModule, LPSTR lpFilename,	DWORD nSize)
extrn GetModuleFileNameA:dword
; BOOL __stdcall FreeLibrary(HMODULE hLibModule)
extrn FreeLibrary:dword
; FARPROC __stdcall GetProcAddress(HMODULE hModule, LPCSTR lpProcName)
extrn GetProcAddress:dword
; HMODULE __stdcall LoadLibraryA(LPCSTR	lpLibFileName)
extrn LoadLibraryA:dword
; BOOL __stdcall GetVersionExA(LPOSVERSIONINFOA	lpVersionInformation)
extrn GetVersionExA:dword
; BOOL __stdcall UnmapViewOfFile(LPCVOID lpBaseAddress)
extrn UnmapViewOfFile:dword
; BOOL __stdcall CloseHandle(HANDLE hObject)
extrn CloseHandle:dword
; BOOL __stdcall ReleaseMutex(HANDLE hMutex)
extrn ReleaseMutex:dword
; BOOL __stdcall SetEvent(HANDLE hEvent)
extrn SetEvent:dword
; DWORD	__stdcall WaitForSingleObject(HANDLE hHandle, DWORD dwMilliseconds)
extrn WaitForSingleObject:dword
; BOOL __stdcall CreateProcessA(LPCSTR lpApplicationName, LPSTR	lpCommandLine, LPSECURITY_ATTRIBUTES lpProcessAttributes, LPSECURITY_ATTRIBUTES	lpThreadAttributes, BOOL bInheritHandles, DWORD	dwCreationFlags, LPVOID	lpEnvironment, LPCSTR lpCurrentDirectory, LPSTARTUPINFOA lpStartupInfo,	LPPROCESS_INFORMATION lpProcessInformation)
extrn CreateProcessA:dword
; LPSTR	__stdcall lstrcpynA(LPSTR lpString1, LPCSTR lpString2, int iMaxLength)
extrn lstrcpynA:dword
; DWORD	__stdcall GetCurrentProcessId()
extrn GetCurrentProcessId:dword
; BOOL __stdcall DuplicateHandle(HANDLE	hSourceProcessHandle, HANDLE hSourceHandle, HANDLE hTargetProcessHandle, LPHANDLE lpTargetHandle, DWORD	dwDesiredAccess, BOOL bInheritHandle, DWORD dwOptions)
extrn DuplicateHandle:dword
; HANDLE __stdcall GetCurrentProcess()
extrn GetCurrentProcess:dword
; HANDLE __stdcall CreateMutexA(LPSECURITY_ATTRIBUTES lpMutexAttributes, BOOL bInitialOwner, LPCSTR lpName)
extrn CreateMutexA:dword
; LPVOID __stdcall MapViewOfFile(HANDLE	hFileMappingObject, DWORD dwDesiredAccess, DWORD dwFileOffsetHigh, DWORD dwFileOffsetLow, SIZE_T dwNumberOfBytesToMap)
extrn MapViewOfFile:dword
; HANDLE __stdcall CreateFileMappingA(HANDLE hFile, LPSECURITY_ATTRIBUTES lpFileMappingAttributes, DWORD flProtect, DWORD dwMaximumSizeHigh, DWORD dwMaximumSizeLow, LPCSTR lpName)
extrn CreateFileMappingA:dword
; DWORD	__stdcall WaitForMultipleObjects(DWORD nCount, const HANDLE *lpHandles,	BOOL bWaitAll, DWORD dwMilliseconds)
extrn WaitForMultipleObjects:dword
; DWORD	__stdcall GetModuleFileNameW(HMODULE hModule, LPWSTR lpFilename, DWORD nSize)
extrn GetModuleFileNameW:dword
; HANDLE __stdcall OpenProcess(DWORD dwDesiredAccess, BOOL bInheritHandle, DWORD dwProcessId)
extrn OpenProcess:dword
; DWORD	__stdcall GetLastError()
extrn GetLastError:dword
; LPTOP_LEVEL_EXCEPTION_FILTER __stdcall SetUnhandledExceptionFilter(LPTOP_LEVEL_EXCEPTION_FILTER lpTopLevelExceptionFilter)
extrn SetUnhandledExceptionFilter:dword
; HLOCAL __stdcall LocalFree(HLOCAL hMem)
extrn LocalFree:dword
; HLOCAL __stdcall LocalAlloc(UINT uFlags, SIZE_T uBytes)
extrn LocalAlloc:dword
; HMODULE __stdcall GetModuleHandleA(LPCSTR lpModuleName)
extrn GetModuleHandleA:dword
; void __stdcall ExitThread(DWORD dwExitCode)
extrn ExitThread:dword
; void __stdcall GetStartupInfoA(LPSTARTUPINFOA	lpStartupInfo)
extrn GetStartupInfoA:dword
; UINT __stdcall SetErrorMode(UINT uMode)
extrn SetErrorMode:dword
; BOOL __stdcall TerminateProcess(HANDLE hProcess, UINT	uExitCode)
extrn TerminateProcess:dword
; BOOL __stdcall QueryPerformanceCounter(LARGE_INTEGER *lpPerformanceCount)
extrn QueryPerformanceCounter:dword
; DWORD	__stdcall GetTickCount()
extrn GetTickCount:dword
; void __stdcall GetSystemTimeAsFileTime(LPFILETIME lpSystemTimeAsFileTime)
extrn GetSystemTimeAsFileTime:dword

;
; Imports from SHDOCVW.dll
;
extrn __imp_SHDOCVW_101:dword
extrn __imp_SHDOCVW_158:dword

;
; Imports from SHLWAPI.dll
;
; LSTATUS __stdcall SHGetValueA(HKEY hkey, LPCSTR pszSubKey, LPCSTR pszValue, DWORD *pdwType, void *pvData, DWORD *pcbData)
extrn SHGetValueA:dword
extrn __imp_StopWatchA:dword
; UINT __stdcall WhichPlatform()
extrn WhichPlatform:dword
; BOOL __stdcall IsOS(DWORD dwOS)
extrn IsOS:dword
extrn GetThreadUILanguage:dword
; DWORD	__stdcall GetModuleFileNameW_0(HMODULE hModule,	LPWSTR lpFilename, DWORD nSize)
extrn GetModuleFileNameW_0:dword
; int __stdcall	SHMessageBoxCheckA(HWND	hwnd, LPCSTR pszText, LPCSTR pszCaption, UINT uType, int iDefault, LPCSTR pszRegVal)
extrn SHMessageBoxCheckA:dword
; BOOL __stdcall SHRegGetBoolUSValueA(LPCSTR pszSubKey,	LPCSTR pszValue, BOOL fIgnoreHKCU, BOOL	fDefault)
extrn SHRegGetBoolUSValueA:dword
; BOOL __stdcall PathRemoveFileSpecA(LPSTR pszPath)
extrn PathRemoveFileSpecA:dword
; BOOL __stdcall PathAppendA(LPSTR pszPath, LPCSTR pMore)
extrn PathAppendA:dword
; BOOL __stdcall PathQuoteSpacesA(LPSTR	lpsz)
extrn PathQuoteSpacesA:dword
; LPWSTR __stdcall StrCpyNW(LPWSTR psz1, LPCWSTR psz2, int cchMax)
extrn StrCpyNW:dword
extrn wnsprintfA:dword
; LPSTR	__stdcall PathFindFileNameA(LPCSTR pszPath)
extrn PathFindFileNameA:dword
; LPSTR	__stdcall StrStrIA(LPCSTR lpFirst, LPCSTR lpSrch)
extrn StrStrIA:dword
; DWORD	__stdcall StopWatchMode()
extrn __imp_StopWatchMode:dword

;
; Imports from USER32.dll
;
; HWND __stdcall GetShellWindow()
extrn GetShellWindow:dword
; int __stdcall	GetClassNameA(HWND hWnd, LPSTR lpClassName, int	nMaxCount)
extrn GetClassNameA:dword
; LRESULT __stdcall SendMessageA(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam)
extrn SendMessageA:dword
; BOOL __stdcall PeekMessageA(LPMSG lpMsg, HWND	hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax, UINT wRemoveMsg)
extrn PeekMessageA:dword
; DWORD	__stdcall MsgWaitForMultipleObjects(DWORD nCount, const	HANDLE *pHandles, BOOL fWaitAll, DWORD dwMilliseconds, DWORD dwWakeMask)
extrn MsgWaitForMultipleObjects:dword
; BOOL __stdcall DestroyWindow(HWND hWnd)
extrn DestroyWindow:dword
; BOOL __stdcall TranslateMessage(const	MSG *lpMsg)
extrn TranslateMessage:dword
; LRESULT __stdcall DispatchMessageA(const MSG *lpMsg)
extrn DispatchMessageA:dword
; int __stdcall	LoadStringA(HINSTANCE hInstance, UINT uID, LPSTR lpBuffer, int cchBufferMax)
extrn LoadStringA:dword
; LRESULT __stdcall DefWindowProcA(HWND	hWnd, UINT Msg,	WPARAM wParam, LPARAM lParam)
extrn DefWindowProcA:dword
; ATOM __stdcall RegisterClassA(const WNDCLASSA	*lpWndClass)
extrn RegisterClassA:dword
; HMENU	__stdcall CreateMenu()
extrn CreateMenu:dword
; HWND __stdcall CreateWindowExA(DWORD dwExStyle, LPCSTR lpClassName, LPCSTR lpWindowName, DWORD dwStyle, int X, int Y,	int nWidth, int	nHeight, HWND hWndParent, HMENU	hMenu, HINSTANCE hInstance, LPVOID lpParam)
extrn CreateWindowExA:dword
; BOOL __stdcall ShowWindow(HWND hWnd, int nCmdShow)
extrn ShowWindow:dword
; HWND __stdcall GetForegroundWindow()
extrn GetForegroundWindow:dword
; int wsprintfA(LPSTR, LPCSTR, ...)
extrn wsprintfA:dword

;
; Imports from msvcrt.dll
;
extrn _except_handler3:dword



; Segment type:	Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use32
assume cs:_text
;org 40114Ch
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
dd 2 dup(0)
dd 41107B81h, 0
dd 2, 25h, 15D0h, 9D0h,	0
; char aSoftwareMicr_1[]
aSoftwareMicr_1	db 'Software\Microsoft\Windows\CurrentV'
db 'ersion\Explorer\BrowseNewProcess',0
; char aBrowsenewproce[]
aBrowsenewproce	db 'BrowseNewProcess',0
align 4
; char aIe08x08x[]
aIe08x08x db 'IE-%08X-%08X',0
align 4
; char String2[]
String2	db 'MauiFrame',0
; char WindowName[2]
WindowName db 2	dup(0)
; char ClassName[]
ClassName db 'IEDummyFrame',0
align 4
; char aCompatwarningf[]
aCompatwarningf	db 'CompatWarningFor',0
align 4
; char ProcName[]
ProcName db 'DllRegisterServer',0
align 4
; char LibFileName[]
LibFileName db 'rsabase.dll',0
; char aSoftwareMicros[]
aSoftwareMicros	db 'Software\Microsoft\Cryptography\Def'
db 'aults\Provider\Microsoft Base Crypt'
db 'ographic Provider v1.0',0
align 4
; char aSignature[]
aSignature db 'Signature',0
align 4
; char pszSubKey[]
pszSubKey db 'System\CurrentControlSet\Control\Wi'
db 'ndows',0
align 10h
; char pszValue[]
pszValue db 'CSDVersion',0
align 10h
stru_4012D0 _SCOPETABLE_ENTRY <0FFFFFFFFh, \ ; SEH scope table for function 401887
		   offset loc_4019AF, \
		   offset loc_4019B3>
dword_4012DC dd	35317764h, 20782D20h, 2520732Dh, 75h
dd 0
; const	WCHAR aBrowseui_dll
aBrowseui_dll:
unicode	0, <browseui.dll>,0
aS db 's',0
aHdocvw_dll:
unicode	0, <hdocvw.dll>,0
aM db 'm',0
aShtml_dll:
unicode	0, <shtml.dll>,0
aUrlmon_dll_0:
unicode	0, <urlmon.dll>,0
aW db 'w',0
aIninet_dll:
unicode	0, <ininet.dll>,0
align 4
; char aWatson_microso[]
aWatson_microso	db 'watson.microsoft.com',0
align 10h
; char aSoftwareMicr_0[]
aSoftwareMicr_0	db 'Software\Microsoft\Internet Explore'
db 'r\Main',0
align 4
; char aIewatsonurl[]
aIewatsonurl db	'IEWatsonURL',0
; char aHklmSoftwareMi[]
aHklmSoftwareMi	db 'HKLM\Software\Microsoft\Internet Ex'
db 'plorer\Registration\DigitalProductI'
db 'D',0
; char aHkcuSoftwareMi[]
aHkcuSoftwareMi	db 'HKCU\Software\Microsoft\Office\10.0'
db '\Common\LanguageResources\UILanguag'
db 'e',0
; char aMicrosoftOffic[]
aMicrosoftOffic	db 'Microsoft\Office\10.0\Common',0
align 4
; const	WCHAR psz2
psz2:
unicode	0, <Microsoft Internet Explorer>
aSHU db	'%s -h %u',0
align 4
; char pMore[]
pMore db 'iedw.exe',0
align 4
; char Name[]
Name db	'Iexplore.XPExceptionFilter',0
align 4
; char aIewatsonenable[]
aIewatsonenable	db 'IEWatsonEnabled',0
; char aJscript_dll[]
aJscript_dll db	'jscript.DLL',0
; char aMshtml_dll[11]
aMshtml_dll db 'mshtml.dll',0
align 4
; char aMlang_dll[10]
aMlang_dll db 'mlang.dll',0
align 4
; char aUrlmon_dll[11]
aUrlmon_dll db 'urlmon.dll',0
align 4
; char aWininet_dll[12]
aWininet_dll db	'wininet.dll',0
; char aShdocvw_dll_0[12]
aShdocvw_dll_0 db 'shdocvw.DLL',0
; char aBrowseui_dll_0[13]
aBrowseui_dll_0	db 'browseui.DLL',0
align 4
; char aComctl32_dll[13]
aComctl32_dll db 'comctl32.DLL',0
align 4
; char ModuleName[13]
ModuleName db 'IEXPLORE.EXE',0
align 4
; char aNowait[]
aNowait	db '-nowait',0
; char aNew[]
aNew db	'-new',0
align 4
; char Srch[]
Srch db	'-eval',0
align 4
aBrowserFrameSt	db 'Browser Frame Start',0
__load_config_used dd 48h ; Size
dd 0			; Time stamp
dw 2 dup(0)		; Version: 0.0
dd 0			; GlobalFlagsClear
dd 0			; GlobalFlagsSet
dd 0			; CriticalSectionDefaultTimeout
dd 0			; DeCommitFreeBlockThreshold
dd 0			; DeCommitTotalFreeThreshold
dd 0			; LockPrefixTable
dd 0			; MaximumAllocationSize
dd 0			; VirtualMemoryThreshold
dd 0			; ProcessAffinityMask
dd 0			; ProcessHeapFlags
dw 0			; CSDVersion
dw 0			; Reserved1
dd 0			; EditList
dd offset ___security_cookie ; SecurityCookie
dd offset ___safe_se_handler_table ; SEHandlerTable
dd 1			; SEHandlerCount
dd 53445352h, 4114039Ch, 48061C2Bh, 0D4B2F287h
dd 307415F4h, 1, 70786569h, 65726F6Ch, 6264702Eh
dd 3 dup(0)
___safe_se_handler_table dd rva	loc_40263E
dd 0
db 0


; Attributes: bp-based frame

sub_401609 proc	near

var_20=	dword ptr -20h
Name= byte ptr -1Ch
var_4= dword ptr -4
arg_0= dword ptr  8

mov	edi, edi
push	ebp
mov	ebp, esp
sub	esp, 20h
mov	eax, ___security_cookie
push	ebx
mov	[ebp+var_4], eax
mov	eax, dword_403098
inc	dword_403098
push	esi
mov	esi, [ebp+arg_0]
push	eax
call	ds:GetCurrentThreadId
push	eax
lea	eax, [ebp+Name]
push	offset aIe08x08x ; "IE-%08X-%08X"
push	eax		; LPSTR
call	ds:wsprintfA
add	esp, 10h
lea	eax, [ebp+Name]
push	eax		; lpName
xor	ebx, ebx
push	ebx		; bInitialState
push	ebx		; bManualReset
push	ebx		; lpEventAttributes
call	ds:CreateEventA
cmp	eax, ebx
mov	[ebp+var_20], eax
jz	short loc_401680
push	edi
mov	edi, [esi+8]
add	edi, [esi+4]
push	15h		; cchWideChar
push	edi		; lpWideCharStr
push	0FFFFFFFFh	; cbMultiByte
lea	eax, [ebp+Name]
push	eax		; lpMultiByteStr
push	ebx		; dwFlags
push	ebx		; CodePage
call	ds:MultiByteToWideChar
push	edi		; lpString
call	ds:lstrlenW
lea	eax, [eax+eax+2]
add	[esi+4], eax
pop	edi

loc_401680:
mov	ecx, [ebp+var_4]
mov	eax, [ebp+var_20]
pop	esi
pop	ebx
call	sub_4024D3
leave
retn	4
sub_401609 endp

db 5 dup(0CCh)


; Attributes: bp-based frame

; int __stdcall	sub_401696(LPCSTR lpFirst, LPCSTR lpSrch, int)
sub_401696 proc	near

lpFirst= dword ptr  8
lpSrch=	dword ptr  0Ch
arg_8= dword ptr  10h

mov	edi, edi
push	ebp
mov	ebp, esp
push	esi
push	[ebp+lpSrch]	; lpSrch
push	[ebp+lpFirst]	; lpFirst
call	ds:StrStrIA
mov	esi, eax
test	esi, esi
jz	short loc_4016EC
cmp	esi, [ebp+lpFirst]
jnz	short loc_4016EC
push	[ebp+lpSrch]	; lpString
call	ds:lstrlenA
mov	cl, [eax+esi]
test	cl, cl
jz	short loc_4016C8
cmp	cl, 20h
jnz	short loc_4016EC

loc_4016C8:
cmp	cl, 20h
jnz	short loc_4016D4

loc_4016CD:
inc	eax
cmp	byte ptr [eax+esi], 20h
jz	short loc_4016CD

loc_4016D4:
cmp	[ebp+arg_8], 0
jz	short loc_4016E7
add	eax, esi
push	eax		; lpString2
push	esi		; lpString1
mov	byte ptr [esi],	0
call	ds:lstrcatA

loc_4016E7:
xor	eax, eax
inc	eax
jmp	short loc_4016EE

loc_4016EC:
xor	eax, eax

loc_4016EE:
pop	esi
pop	ebp
retn	0Ch
sub_401696 endp

align 8


; Attributes: bp-based frame

sub_4016F8 proc	near

String1= byte ptr -54h
var_4= dword ptr -4

mov	edi, edi
push	ebp
mov	ebp, esp
sub	esp, 54h
mov	eax, ___security_cookie
mov	[ebp+var_4], eax
call	ds:GetForegroundWindow
test	eax, eax
jz	short loc_401739
push	50h		; nMaxCount
lea	ecx, [ebp+String1]
push	ecx		; lpClassName
push	eax		; hWnd
call	ds:GetClassNameA
test	eax, eax
jle	short loc_401739
push	offset String2	; "MauiFrame"
lea	eax, [ebp+String1]
push	eax		; lpString1
call	ds:lstrcmpiA
test	eax, eax
jnz	short loc_401739
inc	eax
jmp	short loc_40173B

loc_401739:
xor	eax, eax

loc_40173B:
mov	ecx, [ebp+var_4]
call	sub_4024D3
leave
retn
sub_4016F8 endp

db 5 dup(0CCh)


; Attributes: bp-based frame

; int __stdcall	sub_40174A(HINSTANCE hInstance)
sub_40174A proc	near

WndClass= WNDCLASSA ptr	-28h
hInstance= dword ptr  8

mov	edi, edi
push	ebp
mov	ebp, esp
sub	esp, 28h
mov	eax, ds:DefWindowProcA
push	ebx
mov	ebx, [ebp+hInstance]
push	esi
xor	esi, esi
push	edi
mov	[ebp+WndClass.lpfnWndProc], eax
lea	eax, [ebp+WndClass]
mov	edi, offset ClassName ;	"IEDummyFrame"
push	eax		; lpWndClass
mov	[ebp+WndClass.style], esi
mov	[ebp+WndClass.cbClsExtra], esi
mov	[ebp+WndClass.cbWndExtra], esi
mov	[ebp+WndClass.hInstance], ebx
mov	[ebp+WndClass.hIcon], esi
mov	[ebp+WndClass.hCursor],	esi
mov	[ebp+WndClass.hbrBackground], esi
mov	[ebp+WndClass.lpszMenuName], esi
mov	[ebp+WndClass.lpszClassName], edi
call	ds:RegisterClassA
call	ds:CreateMenu
push	esi		; lpParam
push	ebx		; hInstance
push	eax		; hMenu
push	esi		; hWndParent
push	esi		; nHeight
push	esi		; nWidth
mov	eax, 7FF0h
push	eax		; Y
push	eax		; X
push	esi		; dwStyle
push	offset WindowName ; lpWindowName
push	edi		; lpClassName
push	80h		; dwExStyle
call	ds:CreateWindowExA
mov	esi, eax
push	8		; nCmdShow
push	esi		; hWnd
call	ds:ShowWindow
pop	edi
mov	eax, esi
pop	esi
pop	ebx
leave
retn	4
sub_40174A endp

db 5 dup(0CCh)


; Attributes: bp-based frame

; int __stdcall	sub_4017CA(HINSTANCE hInstance)
sub_4017CA proc	near

pszText= byte ptr -70Ch
pszCaption= byte ptr -30Ch
pszPath= byte ptr -20Ch
pszRegVal= byte	ptr -108h
var_4= dword ptr -4
hInstance= dword ptr  8

mov	edi, edi
push	ebp
mov	ebp, esp
sub	esp, 70Ch
mov	eax, ___security_cookie
push	esi
push	edi
mov	edi, [ebp+hInstance]
mov	[ebp+var_4], eax
push	104h		; nSize
lea	eax, [ebp+pszPath]
push	eax		; lpFilename
push	0		; hModule
call	ds:GetModuleFileNameA
lea	eax, [ebp+pszPath]
push	eax		; pszPath
call	ds:PathFindFileNameA
mov	esi, eax
push	offset aCompatwarningf ; "CompatWarningFor"
lea	eax, [ebp+pszRegVal]
push	eax		; lpString1
call	ds:lstrcpyA
push	esi		; lpString2
lea	eax, [ebp+pszRegVal]
push	eax		; lpString1
call	ds:lstrcatA
mov	esi, ds:LoadStringA
push	0FFh		; cchBufferMax
lea	eax, [ebp+pszCaption]
push	eax		; lpBuffer
push	2BDh		; uID
push	edi		; hInstance
call	esi ; LoadStringA
push	400h		; cchBufferMax
lea	eax, [ebp+pszText]
push	eax		; lpBuffer
push	2BCh		; uID
push	edi		; hInstance
call	esi ; LoadStringA
lea	eax, [ebp+pszRegVal]
push	eax		; pszRegVal
push	0		; iDefault
push	0		; uType
lea	eax, [ebp+pszCaption]
push	eax		; pszCaption
lea	eax, [ebp+pszText]
push	eax		; pszText
push	0		; hwnd
call	ds:SHMessageBoxCheckA
mov	ecx, [ebp+var_4]
pop	edi
pop	esi
call	sub_4024D3
leave
retn	4
sub_4017CA endp

db 5 dup(0CCh)


; Attributes: bp-based frame

sub_401887 proc	near

hLibModule= dword ptr -144h
pvData=	dword ptr -140h
pcbData= dword ptr -13Ch
VersionInformation= _OSVERSIONINFOA ptr	-138h
var_A4=	byte ptr -0A4h
var_1C=	dword ptr -1Ch
ms_exc=	CPPEH_RECORD ptr -18h

push	134h
push	offset stru_4012D0
call	__SEH_prolog
mov	eax, ___security_cookie
mov	[ebp+var_1C], eax
push	25h
pop	ecx
xor	eax, eax
lea	edi, [ebp+VersionInformation]
rep stosd
mov	[ebp+VersionInformation.dwOSVersionInfoSize], 94h
lea	eax, [ebp+VersionInformation]
push	eax		; lpVersionInformation
call	ds:GetVersionExA
test	eax, eax
jz	loc_4019C6
cmp	[ebp+VersionInformation.dwPlatformId], 2
jnz	loc_4019C6
push	4
pop	eax
cmp	[ebp+VersionInformation.dwMajorVersion], eax
jnz	loc_4019C6
and	[ebp+pvData], 0
mov	[ebp+pcbData], eax
lea	eax, [ebp+pcbData]
push	eax		; pcbData
lea	eax, [ebp+pvData]
push	eax		; pvData
push	0		; pdwType
push	offset pszValue	; "CSDVersion"
push	offset pszSubKey ; "System\\CurrentControlSet\\Control\\Win"...
mov	edi, 80000002h
push	edi		; hkey
mov	esi, ds:SHGetValueA
call	esi ; SHGetValueA
test	eax, eax
jnz	loc_4019C6
cmp	word ptr [ebp+pvData], 300h
jnz	loc_4019C6
mov	ebx, 88h
mov	[ebp+pcbData], ebx
lea	eax, [ebp+pcbData]
push	eax		; pcbData
lea	eax, [ebp+var_A4]
push	eax		; pvData
push	0		; pdwType
push	offset aSignature ; "Signature"
push	offset aSoftwareMicros ; "Software\\Microsoft\\Cryptography\\Defa"...
push	edi		; hkey
call	esi ; SHGetValueA
test	eax, eax
jnz	short loc_4019C6
cmp	[ebp+pcbData], ebx
jnz	short loc_4019C6
mov	ecx, ebx
lea	edi, [ebp+var_A4]
mov	esi, offset unk_403008
xor	eax, eax
repe cmpsb
jz	short loc_40197E
sbb	eax, eax
sbb	eax, 0FFFFFFFFh

loc_40197E:
test	eax, eax
jnz	short loc_4019C6
push	offset LibFileName ; "rsabase.dll"
call	ds:LoadLibraryA
mov	[ebp+hLibModule], eax
test	eax, eax
jz	short loc_4019C6
push	offset ProcName	; "DllRegisterServer"
push	eax		; hModule
call	ds:GetProcAddress
test	eax, eax
jz	short loc_4019BA
and	[ebp+ms_exc.registration.TryLevel], 0
call	eax
jmp	short loc_4019B6

loc_4019AF:		; Exception filter 0 for function 401887
xor	eax, eax
inc	eax
retn

loc_4019B3:		; Exception handler 0 for function 401887
mov	esp, [ebp+ms_exc.old_esp]

loc_4019B6:
or	[ebp+ms_exc.registration.TryLevel], 0FFFFFFFFh

loc_4019BA:		; hLibModule
push	[ebp+hLibModule]
call	ds:FreeLibrary

loc_4019C6:
mov	ecx, [ebp+var_1C]
call	sub_4024D3
call	__SEH_epilog
retn
sub_401887 endp

db 5 dup(0CCh)


; Attributes: bp-based frame

; LONG __stdcall TopLevelExceptionFilter(struct	_EXCEPTION_POINTERS *)
TopLevelExceptionFilter	proc near

StartupInfo= _STARTUPINFOA ptr -0AB0h
ProcessInformation= _PROCESS_INFORMATION ptr -0A6Ch
pdwType= dword ptr -0A5Ch
pcbData= dword ptr -0A58h
FileMappingAttributes= _SECURITY_ATTRIBUTES ptr	-0A54h
var_A48= dword ptr -0A48h
var_A44= dword ptr -0A44h
var_A40= dword ptr -0A40h
hObject= dword ptr -0A3Ch
hMutex=	dword ptr -0A38h
hEvent=	dword ptr -0A34h
pvData=	byte ptr -0A30h
CommandLine= byte ptr -20Ch
var_4= dword ptr -4
arg_0= dword ptr  8

mov	edi, edi
push	ebp
mov	ebp, esp
sub	esp, 0AB0h
mov	eax, ___security_cookie
mov	[ebp+var_4], eax
mov	eax, [ebp+arg_0]
push	ebx
xor	ebx, ebx
cmp	eax, ebx
mov	[ebp+var_A40], ebx
jz	short loc_401A0A
mov	eax, [eax]
cmp	dword ptr [eax], 80000003h
jz	loc_401DB3

loc_401A0A:
push	edi
xor	eax, eax
lea	edi, [ebp+FileMappingAttributes]
stosd
stosd
push	ebx		; lpName
push	1C50h		; dwMaximumSizeLow
stosd
push	ebx		; dwMaximumSizeHigh
push	4		; flProtect
lea	eax, [ebp+FileMappingAttributes]
xor	edi, edi
push	eax		; lpFileMappingAttributes
inc	edi
push	0FFFFFFFFh	; hFile
mov	[ebp+FileMappingAttributes.nLength], 0Ch
mov	[ebp+FileMappingAttributes.bInheritHandle], edi
call	ds:CreateFileMappingA
cmp	eax, ebx
mov	[ebp+var_A48], eax
jnz	short loc_401A56
mov	[ebp+var_A40], edi
jmp	loc_401D9E

loc_401A56:
push	esi
push	ebx		; dwNumberOfBytesToMap
push	ebx		; dwFileOffsetLow
push	ebx		; dwFileOffsetHigh
push	6		; dwDesiredAccess
push	eax		; hFileMappingObject
call	ds:MapViewOfFile
mov	esi, eax
cmp	esi, ebx
jnz	short loc_401A74
mov	[ebp+var_A40], edi
jmp	loc_401D92

loc_401A74:		; lpName
push	ebx
xor	eax, eax
push	ebx		; bInitialState
mov	ecx, 714h
mov	edi, esi
rep stosd
mov	edi, ds:CreateEventA
push	ebx		; bManualReset
lea	eax, [ebp+FileMappingAttributes]
push	eax		; lpEventAttributes
call	edi ; CreateEventA
push	ebx		; lpName
push	ebx		; bInitialState
mov	[ebp+hObject], eax
push	ebx		; bManualReset
lea	eax, [ebp+FileMappingAttributes]
push	eax		; lpEventAttributes
call	edi ; CreateEventA
push	ebx		; lpName
mov	[ebp+hEvent], eax
push	ebx		; bInitialOwner
lea	eax, [ebp+FileMappingAttributes]
push	eax		; lpMutexAttributes
call	ds:CreateMutexA
mov	edi, ds:GetCurrentProcess
push	ebx		; dwOptions
push	1		; bInheritHandle
mov	[ebp+hMutex], eax
lea	eax, [esi+24h]
push	1F0FFFh		; dwDesiredAccess
push	eax		; lpTargetHandle
call	edi ; GetCurrentProcess
push	eax		; hTargetProcessHandle
call	edi ; GetCurrentProcess
push	eax		; hSourceHandle
call	edi ; GetCurrentProcess
push	eax		; hSourceProcessHandle
call	ds:DuplicateHandle
test	eax, eax
jz	loc_401D4C
cmp	[ebp+hObject], ebx
jz	loc_401D4C
cmp	[ebp+hEvent], ebx
jz	loc_401D4C
mov	edi, [ebp+hMutex]
cmp	edi, ebx
jz	loc_401D4C
cmp	[esi+24h], ebx
jz	loc_401D4C
call	ds:GetCurrentProcessId
mov	[esi+4], eax
call	ds:GetCurrentThreadId
mov	[esi+8], eax
mov	eax, [ebp+hObject]
mov	[esi+1Ch], eax
mov	eax, [ebp+hEvent]
mov	[esi+14h], eax
mov	eax, [ebp+arg_0]
cmp	eax, ebx
mov	[esi+20h], edi
mov	dword ptr [esi], 1C50h
mov	[esi+10h], eax
jz	short loc_401B55
mov	eax, [eax]
mov	eax, [eax+0Ch]
mov	[esi+0Ch], eax

loc_401B55:
mov	dword ptr [esi+34h], 3
call	ds:GetThreadUILanguage
movzx	eax, ax
push	38h		; cchMax
mov	[esi+1144h], eax
push	offset psz2	; "Microsoft Internet Explorer"
lea	eax, [esi+48h]
push	eax		; psz1
call	ds:StrCpyNW
push	0C8h		; iMaxLength
push	offset aMicrosoftOffic ; "Microsoft\\Office\\10.0\\Common"
lea	eax, [esi+1148h]
push	eax		; lpString1
call	ds:lstrcpynA
mov	edi, 104h
push	edi		; iMaxLength
push	offset aHkcuSoftwareMi ; "HKCU\\Software\\Microsoft\\Office\\10.0"...
lea	eax, [esi+0F3Ch]
push	eax		; lpString1
call	ds:lstrcpynA
push	edi		; iMaxLength
push	offset aHklmSoftwareMi ; "HKLM\\Software\\Microsoft\\Internet Exp"...
lea	eax, [esi+1040h]
push	eax		; lpString1
call	ds:lstrcpynA
lea	eax, [ebp+pcbData]
push	eax		; pcbData
lea	eax, [ebp+pvData]
push	eax		; pvData
lea	eax, [ebp+pdwType]
push	eax		; pdwType
push	offset aIewatsonurl ; "IEWatsonURL"
push	offset aSoftwareMicr_0 ; "Software\\Microsoft\\Internet	Explorer\"...
push	80000002h	; hkey
mov	[ebp+pcbData], 824h
call	ds:SHGetValueA
test	eax, eax
push	edi		; iMaxLength
jnz	short loc_401C00
lea	eax, [ebp+pvData]
push	eax
jmp	short loc_401C05

loc_401C00:		; "watson.microsoft.com"
push	offset aWatson_microso

loc_401C05:
lea	eax, [esi+0E38h]
push	eax		; lpString1
call	ds:lstrcpynA
push	edi		; cchMax
push	offset aBrowseui_dll ; "browseui.dll"
lea	eax, [esi+1210h]
push	eax		; psz1
call	ds:StrCpyNW
push	edi		; nSize
lea	eax, [esi+0B8h]
push	eax		; lpFilename
push	ebx		; hModule
call	ds:GetModuleFileNameW_0
push	11h
xor	eax, eax
pop	ecx
push	[ebp+var_A48]
lea	edi, [ebp+StartupInfo]
rep stosd
lea	edi, [ebp+ProcessInformation]
stosd
stosd
stosd
push	offset dword_4012DC
stosd
lea	eax, [ebp+CommandLine]
push	208h
push	eax
mov	[ebp+StartupInfo.cb], 44h
call	ds:wnsprintfA
add	esp, 10h
lea	eax, [ebp+ProcessInformation]
push	eax		; lpProcessInformation
lea	eax, [ebp+StartupInfo]
push	eax		; lpStartupInfo
push	ebx		; lpCurrentDirectory
push	ebx		; lpEnvironment
push	4000020h	; dwCreationFlags
xor	edi, edi
inc	edi
push	edi		; bInheritHandles
push	ebx		; lpThreadAttributes
push	ebx		; lpProcessAttributes
lea	eax, [ebp+CommandLine]
push	eax		; lpCommandLine
push	ebx		; lpApplicationName
call	ds:CreateProcessA
test	eax, eax
jz	loc_401D56
mov	[ebp+var_A44], edi
mov	edi, ds:WaitForSingleObject

loc_401CB2:		; dwMilliseconds
push	4E20h
push	[ebp+hObject]	; hHandle
call	edi ; WaitForSingleObject
test	eax, eax
jnz	short loc_401CD9
push	1		; dwMilliseconds
push	[ebp+hEvent]	; hHandle
call	edi ; WaitForSingleObject
test	eax, eax
jnz	short loc_401D30
mov	[ebp+var_A44], ebx
jmp	short loc_401D30

loc_401CD9:		; dwMilliseconds
push	4E20h
push	[ebp+hMutex]	; hHandle
call	edi ; WaitForSingleObject
cmp	eax, 102h
jz	short loc_401D56
cmp	eax, 80h
jz	short loc_401D3E
push	1		; dwMilliseconds
push	[ebp+hObject]	; hHandle
call	edi ; WaitForSingleObject
test	eax, eax
jz	short loc_401D10
push	[ebp+hEvent]	; hEvent
call	ds:SetEvent
jmp	short loc_401D1E

loc_401D10:		; dwMilliseconds
push	1
push	[ebp+hEvent]	; hHandle
call	edi ; WaitForSingleObject
test	eax, eax
jnz	short loc_401D24

loc_401D1E:
mov	[ebp+var_A44], ebx

loc_401D24:		; hMutex
push	[ebp+hMutex]
call	ds:ReleaseMutex

loc_401D30:
cmp	[ebp+var_A44], ebx
jnz	loc_401CB2
jmp	short loc_401D56

loc_401D3E:		; hMutex
push	[ebp+hMutex]
call	ds:ReleaseMutex
jmp	short loc_401D56

loc_401D4C:
mov	[ebp+var_A40], 1

loc_401D56:
cmp	[ebp+hObject], ebx
jz	short loc_401D6A
push	[ebp+hObject]	; hObject
call	ds:CloseHandle

loc_401D6A:
cmp	[ebp+hEvent], ebx
jz	short loc_401D7E
push	[ebp+hEvent]	; hObject
call	ds:CloseHandle

loc_401D7E:
cmp	[ebp+hMutex], ebx
jz	short loc_401D92
push	[ebp+hMutex]	; hObject
call	ds:CloseHandle

loc_401D92:
cmp	esi, ebx
jz	short loc_401D9D
push	esi		; lpBaseAddress
call	ds:UnmapViewOfFile

loc_401D9D:
pop	esi

loc_401D9E:
cmp	[ebp+var_A48], ebx
pop	edi
jz	short loc_401DB3
push	[ebp+var_A48]	; hObject
call	ds:CloseHandle

loc_401DB3:
mov	ecx, [ebp+var_4]
mov	eax, [ebp+var_A40]
pop	ebx
call	sub_4024D3
leave
retn	4
TopLevelExceptionFilter	endp

db 5 dup(0CCh)



sub_401DCB proc	near
push	0
push	0
push	60000023h
call	SHDOCVW_158
neg	eax
sbb	eax, eax
inc	eax
retn
sub_401DCB endp

db 5 dup(0CCh)


; Attributes: bp-based frame

; LONG __stdcall sub_401DE4(struct _EXCEPTION_POINTERS *)
sub_401DE4 proc	near

StartupInfo= _STARTUPINFOA ptr -388h
Handles= dword ptr -344h
var_340= dword ptr -340h
var_33C= dword ptr -33Ch
ProcessInformation= _PROCESS_INFORMATION ptr -338h
var_328= dword ptr -328h
FileMappingAttributes= _SECURITY_ATTRIBUTES ptr	-324h
hObject= dword ptr -318h
var_314= dword ptr -314h
CommandLine= byte ptr -310h
sz= byte ptr -108h
var_4= dword ptr -4
arg_0= dword ptr  8

mov	edi, edi
push	ebp
mov	ebp, esp
sub	esp, 388h
mov	eax, ___security_cookie
push	ebx
xor	ebx, ebx
push	offset Name	; "Iexplore.XPExceptionFilter"
push	ebx		; bInitialOwner
push	ebx		; lpMutexAttributes
mov	[ebp+var_4], eax
mov	[ebp+var_314], ebx
call	ds:CreateMutexA
cmp	eax, ebx
mov	[ebp+var_328], eax
jz	loc_40207C
call	ds:GetLastError
cmp	eax, 0B7h
jnz	short loc_401E37
mov	[ebp+var_314], 1
jmp	loc_402070

loc_401E37:
push	edi
push	10h
pop	ecx
xor	eax, eax
lea	edi, [ebp+StartupInfo.lpReserved]
rep stosd
mov	[ebp+ProcessInformation.hProcess], ebx
lea	edi, [ebp+ProcessInformation.hThread]
stosd
stosd
stosd
push	ebx		; lpName
xor	eax, eax
push	220h		; dwMaximumSizeLow
lea	edi, [ebp+FileMappingAttributes.lpSecurityDescriptor]
stosd
push	ebx		; dwMaximumSizeHigh
stosd
push	4		; flProtect
lea	eax, [ebp+FileMappingAttributes]
push	eax		; lpFileMappingAttributes
push	0FFFFFFFFh	; hFile
mov	[ebp+StartupInfo.cb], 44h
mov	[ebp+FileMappingAttributes.nLength], 0Ch
mov	[ebp+FileMappingAttributes.bInheritHandle], 1
call	ds:CreateFileMappingA
cmp	eax, ebx
mov	[ebp+hObject], eax
jz	loc_40206F
push	esi
push	ebx		; dwNumberOfBytesToMap
push	ebx		; dwFileOffsetLow
push	ebx		; dwFileOffsetHigh
push	6		; dwDesiredAccess
push	eax		; hFileMappingObject
call	ds:MapViewOfFile
mov	esi, eax
cmp	esi, ebx
jz	loc_402062
xor	eax, eax
mov	ecx, 88h
mov	edi, esi
rep stosd
mov	edi, ds:GetCurrentProcessId
call	edi ; GetCurrentProcessId
push	eax		; dwProcessId
push	1		; bInheritHandle
push	100411h		; dwDesiredAccess
call	ds:OpenProcess
push	ebx		; lpName
push	ebx		; bInitialState
mov	[esi], eax
push	ebx		; bManualReset
lea	eax, [ebp+FileMappingAttributes]
push	eax		; lpEventAttributes
call	ds:CreateEventA
push	ebx		; lpName
push	ebx		; bInitialState
mov	[esi+10h], eax
push	ebx		; bManualReset
lea	eax, [ebp+FileMappingAttributes]
push	eax		; lpEventAttributes
call	ds:CreateEventA
mov	[esi+14h], eax
call	edi ; GetCurrentProcessId
mov	[esi+4], eax
call	ds:GetCurrentThreadId
mov	[esi+8], eax
mov	eax, [ebp+arg_0]
mov	[esi+0Ch], eax
mov	edi, 104h
push	edi		; nSize
lea	eax, [esi+18h]
push	eax		; lpFilename
push	ebx		; hModule
call	ds:GetModuleFileNameW
cmp	[esi+10h], ebx
jz	loc_40205B
cmp	[esi+14h], ebx
jz	loc_40205B
cmp	[esi], ebx
jz	loc_40205B
push	edi		; nSize
lea	eax, [ebp+sz]
push	eax		; lpFilename
push	ebx		; hModule
mov	[ebp+sz], bl
call	ds:GetModuleFileNameA
test	eax, eax
jz	loc_402047
lea	eax, [ebp+sz]
push	eax		; pszPath
call	ds:PathRemoveFileSpecA
push	offset pMore	; "iedw.exe"
lea	eax, [ebp+sz]
push	eax		; pszPath
call	ds:PathAppendA
test	eax, eax
jz	loc_402047
lea	eax, [ebp+sz]
push	eax		; lpsz
mov	[ebp+CommandLine], bl
call	ds:PathQuoteSpacesA
push	[ebp+hObject]
lea	eax, [ebp+sz]
push	eax
push	offset aSHU	; "%s -h %u"
lea	eax, [ebp+CommandLine]
push	208h
push	eax
call	ds:wnsprintfA
add	esp, 14h
test	eax, eax
jl	loc_402047
lea	eax, [ebp+ProcessInformation]
push	eax		; lpProcessInformation
lea	eax, [ebp+StartupInfo]
push	eax		; lpStartupInfo
push	ebx		; lpCurrentDirectory
push	ebx		; lpEnvironment
push	4000020h	; dwCreationFlags
xor	edi, edi
inc	edi
push	edi		; bInheritHandles
push	ebx		; lpThreadAttributes
push	ebx		; lpProcessAttributes
lea	eax, [ebp+CommandLine]
push	eax		; lpCommandLine
push	ebx		; lpApplicationName
call	ds:CreateProcessA
test	eax, eax
jz	short loc_402047
mov	eax, [esi+10h]
mov	[ebp+Handles], eax
mov	eax, [esi+14h]
mov	[ebp+var_340], eax
mov	eax, [ebp+ProcessInformation.hProcess]
push	1D4C0h		; dwMilliseconds
mov	[ebp+var_33C], eax
push	ebx		; bWaitAll
lea	eax, [ebp+Handles]
push	eax		; lpHandles
push	3		; nCount
call	ds:WaitForMultipleObjects
test	eax, eax
jnz	short loc_402031
mov	[ebp+var_314], edi

loc_402031:		; hObject
push	[ebp+ProcessInformation.hProcess]
mov	edi, ds:CloseHandle
call	edi ; CloseHandle
push	[ebp+ProcessInformation.hThread] ; hObject
call	edi ; CloseHandle

loc_402047:		; hObject
push	dword ptr [esi+10h]
mov	edi, ds:CloseHandle
call	edi ; CloseHandle
push	dword ptr [esi+14h] ; hObject
call	edi ; CloseHandle
push	dword ptr [esi]	; hObject
call	edi ; CloseHandle

loc_40205B:		; lpBaseAddress
push	esi
call	ds:UnmapViewOfFile

loc_402062:		; hObject
push	[ebp+hObject]
call	ds:CloseHandle
pop	esi

loc_40206F:
pop	edi

loc_402070:		; hObject
push	[ebp+var_328]
call	ds:CloseHandle

loc_40207C:
mov	ecx, [ebp+var_4]
mov	eax, [ebp+var_314]
pop	ebx
call	sub_4024D3
leave
retn	4
sub_401DE4 endp

db 5 dup(0CCh)


; Attributes: bp-based frame

; int __stdcall	sub_402094(HWND	pcbData, int, LPCSTR pHandles, LPCWSTR hMem)
sub_402094 proc	near

Msg= MSG ptr -34h
lParam=	dword ptr -18h
var_14=	dword ptr -14h
var_10=	dword ptr -10h
pdwType= dword ptr -0Ch
pvData=	dword ptr -8
var_4= dword ptr -4
pcbData= dword ptr  8
pHandles= dword	ptr  10h
hMem= dword ptr	 14h

mov	edi, edi
push	ebp
mov	ebp, esp
sub	esp, 34h
push	ebx
push	esi
push	edi
xor	edi, edi
mov	[ebp+pdwType], 1
mov	[ebp+var_4], edi
xor	esi, esi
mov	[ebp+pvData], edi

loc_4020B0:
mov	ebx, [ebp+pHandles]
push	1		; int
push	offset Srch	; "-eval"
push	ebx		; lpFirst
call	sub_401696
test	eax, eax
jz	short loc_4020CC
xor	esi, esi
inc	esi
mov	[ebp+pvData], esi
jmp	short loc_4020B0

loc_4020CC:		; int
push	1
push	offset aNew	; "-new"
push	ebx		; lpFirst
call	sub_401696
test	eax, eax
jz	short loc_4020E2
xor	esi, esi
inc	esi
jmp	short loc_4020B0

loc_4020E2:		; int
push	1
push	offset aNowait	; "-nowait"
push	ebx		; lpFirst
call	sub_401696
test	eax, eax
jz	short loc_4020FC
mov	[ebp+var_4], 1
jmp	short loc_4020B0

loc_4020FC:		; "IEXPLORE.EXE"
push	offset ModuleName
call	ds:GetModuleHandleA
test	eax, eax
jnz	short loc_402111
xor	esi, esi
inc	esi
mov	[ebp+pvData], esi

loc_402111:
cmp	esi, edi
jnz	loc_4022A6
push	edi		; fDefault
push	edi		; fIgnoreHKCU
push	offset aBrowsenewproce ; "BrowseNewProcess"
push	offset aSoftwareMicr_1 ; "Software\\Microsoft\\Windows\\CurrentVe"...
call	ds:SHRegGetBoolUSValueA
test	eax, eax
jnz	loc_4022A6
call	ds:WhichPlatform
cmp	eax, 2
jnz	loc_4022A6
call	ds:GetShellWindow
mov	esi, eax
cmp	esi, edi
jz	loc_4022A6
mov	eax, [ebp+hMem]
push	109Ch		; uBytes
push	40h		; uFlags
mov	[ebp+lParam], eax
call	ds:LocalAlloc
cmp	eax, edi
mov	[ebp+hMem], eax
jz	loc_402375
push	824h		; cchWideChar
push	eax		; lpWideCharStr
push	0FFFFFFFFh	; cbMultiByte
push	ebx		; lpMultiByteStr
push	edi		; dwFlags
push	edi		; CodePage
call	ds:MultiByteToWideChar
mov	eax, [ebp+hMem]
push	eax		; lpString
mov	[ebp+var_10], eax
call	ds:lstrlenW
lea	eax, [eax+eax+2]
mov	[ebp+var_14], eax
lea	eax, [ebp+lParam]
push	eax
call	sub_401609
cmp	eax, edi
mov	[ebp+pvData], eax
jz	loc_40228F
cmp	byte ptr [ebx],	0
mov	[ebp+pHandles],	edi
jnz	short loc_4021BA
call	sub_4016F8
test	eax, eax
jz	short loc_4021CB

loc_4021BA:
cmp	[ebp+var_4], edi
jnz	short loc_4021CB
lea	eax, [ebp+lParam]
push	eax
call	sub_401609
mov	[ebp+pHandles],	eax

loc_4021CB:
cmp	[ebp+pHandles],	edi
jnz	short loc_4021DE
cmp	byte ptr [ebx],	0
jz	short loc_4021DE
cmp	[ebp+var_4], edi
jz	loc_402286

loc_4021DE:
lea	eax, [ebp+lParam]
push	eax		; lParam
push	esi		; wParam
push	4Ah		; Msg
push	esi		; hWnd
call	ds:SendMessageA
push	[ebp+hMem]	; hMem
mov	esi, eax
call	ds:LocalFree
cmp	esi, edi
mov	[ebp+hMem], edi
jz	short loc_402278
push	2710h		; dwMilliseconds
push	[ebp+pvData]	; hHandle
call	ds:WaitForSingleObject
cmp	[ebp+pHandles],	edi
jz	short loc_402286
push	[ebp+pcbData]	; hInstance
call	sub_40174A
mov	esi, ds:PeekMessageA
mov	[ebp+pcbData], eax

loc_402222:		; dwWakeMask
push	0FFh
push	0FFFFFFFFh	; dwMilliseconds
push	edi		; fWaitAll
lea	eax, [ebp+pHandles]
push	eax		; pHandles
push	1		; nCount
call	ds:MsgWaitForMultipleObjects
mov	ebx, eax
cmp	ebx, edi
jnz	short loc_402261
push	[ebp+pcbData]	; hWnd
call	ds:DestroyWindow
jmp	short loc_402261

loc_402247:
cmp	[ebp+Msg.message], 12h
jz	short loc_402272
lea	eax, [ebp+Msg]
push	eax		; lpMsg
call	ds:TranslateMessage
lea	eax, [ebp+Msg]
push	eax		; lpMsg
call	ds:DispatchMessageA

loc_402261:		; wRemoveMsg
push	1
push	edi		; wMsgFilterMax
push	edi		; wMsgFilterMin
lea	eax, [ebp+Msg]
push	edi		; hWnd
push	eax		; lpMsg
call	esi ; PeekMessageA
test	eax, eax
jnz	short loc_402247
jmp	short loc_402274

loc_402272:
xor	ebx, ebx

loc_402274:
cmp	ebx, edi
jnz	short loc_402222

loc_402278:
cmp	[ebp+pHandles],	edi
jz	short loc_402286
push	[ebp+pHandles]	; hObject
call	ds:CloseHandle

loc_402286:		; hObject
push	[ebp+pvData]
call	ds:CloseHandle

loc_40228F:
cmp	[ebp+hMem], edi
jz	loc_402375
push	[ebp+hMem]	; hMem
call	ds:LocalFree
jmp	loc_402375

loc_4022A6:
call	sub_401887
cmp	[ebp+pvData], edi
jz	short loc_4022F6
push	[ebp+pcbData]	; hInstance
call	sub_4017CA
mov	esi, ds:LoadLibraryA
push	offset aComctl32_dll ; "comctl32.DLL"
call	esi ; LoadLibraryA
push	offset aBrowseui_dll_0 ; "browseui.DLL"
call	esi ; LoadLibraryA
push	offset aShdocvw_dll_0 ;	"shdocvw.DLL"
call	esi ; LoadLibraryA
push	offset aWininet_dll ; "wininet.dll"
call	esi ; LoadLibraryA
push	offset aUrlmon_dll ; "urlmon.dll"
call	esi ; LoadLibraryA
push	offset aMlang_dll ; "mlang.dll"
call	esi ; LoadLibraryA
push	offset aMshtml_dll ; "mshtml.dll"
call	esi ; LoadLibraryA
push	offset aJscript_dll ; "jscript.DLL"
call	esi ; LoadLibraryA

loc_4022F6:		; dwOS
push	12h
call	ds:IsOS
test	eax, eax
jnz	short loc_40237F
mov	esi, ds:SHGetValueA
lea	eax, [ebp+pcbData]
push	eax		; pcbData
lea	eax, [ebp+pvData]
push	eax		; pvData
lea	eax, [ebp+pdwType]
push	eax		; pdwType
mov	ebx, offset aIewatsonenable ; "IEWatsonEnabled"
push	ebx		; pszValue
mov	edi, offset aSoftwareMicr_0 ; "Software\\Microsoft\\Internet Explorer\"...
push	edi		; pszSubKey
push	80000002h	; hkey
mov	[ebp+pvData], 1
mov	[ebp+pcbData], 4
call	esi ; SHGetValueA
test	eax, eax
jz	short loc_402355
lea	eax, [ebp+pcbData]
push	eax		; pcbData
lea	eax, [ebp+pvData]
push	eax		; pvData
lea	eax, [ebp+pdwType]
push	eax		; pdwType
push	ebx		; pszValue
push	edi		; pszSubKey
push	80000001h	; hkey
mov	[ebp+pcbData], 4
call	esi ; SHGetValueA

loc_402355:
cmp	[ebp+pvData], 0
jz	short loc_402366
push	offset TopLevelExceptionFilter ; lpTopLevelExceptionFilter
call	ds:SetUnhandledExceptionFilter

loc_402366:
mov	ebx, [ebp+pHandles]

loc_402369:
push	[ebp+hMem]
push	ebx
call	SHDOCVW_101
mov	[ebp+pdwType], eax

loc_402375:
mov	eax, [ebp+pdwType]
pop	edi
pop	esi
pop	ebx
leave
retn	10h

loc_40237F:
call	sub_401DCB
test	eax, eax
jz	short loc_402369
push	offset sub_401DE4 ; lpTopLevelExceptionFilter
call	ds:SetUnhandledExceptionFilter
jmp	short loc_402369
sub_402094 endp

db 5 dup(0CCh)
; Exported entry   1. DllGetLCID



public DllGetLCID
DllGetLCID proc	near
call	ds:GetThreadUILanguage
movzx	eax, ax
retn	4
DllGetLCID endp

db 5 dup(0CCh)


; Attributes: noreturn bp-based	frame

sub_4023AB proc	near

StartupInfo= _STARTUPINFOA ptr -44h

mov	edi, edi
push	ebp
mov	ebp, esp
sub	esp, 44h
push	esi
call	ds:GetCommandLineA
push	1		; uMode
mov	esi, eax
call	ds:SetErrorMode
call	StopWatchMode
test	al, 8
jz	short loc_4023DF
push	0
push	0Ah
push	1
push	offset aBrowserFrameSt ; "Browser Frame	Start"
push	4
call	StopWatchA

loc_4023DF:
mov	al, [esi]
cmp	al, 22h
jnz	short loc_4023F7

loc_4023E5:
inc	esi
mov	al, [esi]
test	al, al
jz	short loc_4023F0
cmp	al, 22h
jnz	short loc_4023E5

loc_4023F0:
cmp	byte ptr [esi],	22h
jnz	short loc_402408
jmp	short loc_402407

loc_4023F7:
cmp	al, 20h
jbe	short loc_402408

loc_4023FB:
inc	esi
cmp	byte ptr [esi],	20h
ja	short loc_4023FB
jmp	short loc_402408

loc_402403:
cmp	al, 20h
ja	short loc_40240E

loc_402407:
inc	esi

loc_402408:
mov	al, [esi]
test	al, al
jnz	short loc_402403

loc_40240E:
and	[ebp+StartupInfo.dwFlags], 0
lea	eax, [ebp+StartupInfo]
push	eax		; lpStartupInfo
mov	[ebp+StartupInfo.cb], 44h
call	ds:GetStartupInfoA
test	byte ptr [ebp+StartupInfo.dwFlags], 1
jz	short loc_40242F
movzx	eax, [ebp+StartupInfo.wShowWindow]
jmp	short loc_402432

loc_40242F:
push	0Ah
pop	eax

loc_402432:		; hMem
push	eax
push	esi		; pHandles
push	0		; int
push	0		; lpModuleName
call	ds:GetModuleHandleA
push	eax		; pcbData
call	sub_402094
push	eax		; dwExitCode
call	ds:ExitThread
sub_4023AB endp

db 6 dup(0CCh)
assume fs:nothing, gs:nothing
; [0000000A BYTES: COLLAPSED FUNCTION start. PRESS KEYPAD CTRL-"+" TO EXPAND]
align 10h


; Attributes: bp-based frame

sub_402460 proc	near

PerformanceCount= LARGE_INTEGER	ptr -10h
SystemTimeAsFileTime= _FILETIME	ptr -8

mov	edi, edi
push	ebp
mov	ebp, esp
sub	esp, 10h
mov	eax, ___security_cookie
test	eax, eax
jz	short loc_402478
cmp	eax, 0BB40h
jnz	short loc_4024C5

loc_402478:
push	esi
lea	eax, [ebp+SystemTimeAsFileTime]
push	eax		; lpSystemTimeAsFileTime
call	ds:GetSystemTimeAsFileTime
mov	esi, [ebp+SystemTimeAsFileTime.dwHighDateTime]
xor	esi, [ebp+SystemTimeAsFileTime.dwLowDateTime]
call	ds:GetCurrentProcessId
xor	esi, eax
call	ds:GetCurrentThreadId
xor	esi, eax
call	ds:GetTickCount
xor	esi, eax
lea	eax, [ebp+PerformanceCount]
push	eax		; lpPerformanceCount
call	ds:QueryPerformanceCounter
mov	eax, dword ptr [ebp+PerformanceCount+4]
xor	eax, dword ptr [ebp+PerformanceCount]
xor	eax, esi
and	eax, 0FFFFh
pop	esi
jnz	short loc_4024C0
mov	eax, 0BB40h

loc_4024C0:
mov	___security_cookie, eax

loc_4024C5:
not	eax
mov	dword_403090, eax
leave
retn
sub_402460 endp

db 5 dup(0CCh)



sub_4024D3 proc	near
cmp	ecx, ___security_cookie
jnz	short loc_4024E4
test	ecx, 0FFFF0000h
jnz	short loc_4024E4
retn

loc_4024E4:
jmp	loc_4024EE
db 5 dup(0CCh)

loc_4024EE:
mov	edi, edi
push	ebp
mov	ebp, esp
sub	esp, 330h
push	edi
mov	[ebp-228h], eax
mov	[ebp-22Ch], ecx
mov	[ebp-230h], edx
mov	[ebp-234h], ebx
mov	[ebp-238h], esi
mov	[ebp-23Ch], edi
mov	word ptr [ebp-210h], ss
mov	word ptr [ebp-21Ch], cs
mov	word ptr [ebp-240h], ds
mov	word ptr [ebp-244h], es
mov	word ptr [ebp-248h], fs
mov	word ptr [ebp-24Ch], gs
pushf
pop	dword ptr [ebp-218h]
mov	dword ptr [ebp-2D8h], 10001h
mov	eax, [ebp+4]
mov	[ebp-220h], eax
lea	eax, [ebp+4]
mov	[ebp-214h], eax
lea	eax, [ebp+4]
mov	eax, [eax-4]
mov	[ebp-224h], eax
push	14h
pop	ecx
xor	eax, eax
lea	edi, [ebp-330h]
rep stosd
mov	dword ptr [ebp-330h], 0C0000409h
mov	eax, [ebp+4]
mov	[ebp-324h], eax
lea	eax, [ebp-330h]
mov	[ebp-8], eax
lea	eax, [ebp-2D8h]
mov	[ebp-4], eax
mov	eax, ___security_cookie
mov	[ebp-2E0h], eax
mov	eax, dword_403090
mov	[ebp-2DCh], eax
push	0		; lpTopLevelExceptionFilter
call	ds:SetUnhandledExceptionFilter
lea	eax, [ebp-8]
push	eax		; ExceptionInfo
call	ds:UnhandledExceptionFilter
push	502h		; uExitCode
call	ds:GetCurrentProcess
push	eax		; hProcess
call	ds:TerminateProcess
pop	edi
leave
retn
sub_4024D3 endp

db 6 dup(0CCh)
; [0000003B BYTES: COLLAPSED FUNCTION __SEH_prolog. PRESS KEYPAD CTRL-"+" TO EXPAND]
; [00000011 BYTES: COLLAPSED FUNCTION __SEH_epilog. PRESS KEYPAD CTRL-"+" TO EXPAND]
db 6 dup(0CCh)

loc_40263E:
jmp	ds:_except_handler3
db 6 dup(0CCh)
; [00000006 BYTES: COLLAPSED FUNCTION StopWatchA. PRESS	KEYPAD CTRL-"+"	TO EXPAND]
db 6 dup(0CCh)
; [00000006 BYTES: COLLAPSED FUNCTION StopWatchMode. PRESS KEYPAD CTRL-"+" TO EXPAND]
db 6 dup(0CCh)
; [00000006 BYTES: COLLAPSED FUNCTION SHDOCVW_158. PRESS KEYPAD	CTRL-"+" TO EXPAND]
db 6 dup(0CCh)
; [00000006 BYTES: COLLAPSED FUNCTION SHDOCVW_101. PRESS KEYPAD	CTRL-"+" TO EXPAND]
__IMPORT_DESCRIPTOR_msvcrt dd rva off_402830 ; Import Name Table
dd 0FFFFFFFFh		; Time stamp
dd 0FFFFFFFFh		; Forwarder Chain
dd rva aMsvcrt_dll	; DLL Name
dd rva _except_handler3	; Import Address Table
__IMPORT_DESCRIPTOR_KERNEL32 dd	rva off_4026EC ; Import	Name Table
dd 0FFFFFFFFh		; Time stamp
dd 0FFFFFFFFh		; Forwarder Chain
dd rva aKernel32_dll	; DLL Name
dd rva UnhandledExceptionFilter	; Import Address Table
__IMPORT_DESCRIPTOR_USER32 dd rva off_4027EC ; Import Name Table
dd 0FFFFFFFFh		; Time stamp
dd 0FFFFFFFFh		; Forwarder Chain
dd rva aUser32_dll	; DLL Name
dd rva GetShellWindow	; Import Address Table
__IMPORT_DESCRIPTOR_SHLWAPI dd rva off_4027A8 ;	Import Name Table
dd 0FFFFFFFFh		; Time stamp
dd 0FFFFFFFFh		; Forwarder Chain
dd rva aShlwapi_dll	; DLL Name
dd rva SHGetValueA	; Import Address Table
__IMPORT_DESCRIPTOR_SHDOCVW dd rva dword_40279C	; Import Name Table
dd 0FFFFFFFFh		; Time stamp
dd 0FFFFFFFFh		; Forwarder Chain
dd rva aShdocvw_dll	; DLL Name
dd rva __imp_SHDOCVW_101 ; Import Address Table
dd 5 dup(0)
;
; Import names for KERNEL32.dll
;
off_4026EC dd rva word_402B4A
dd rva word_402AE0
dd rva word_402866
dd rva word_402872
dd rva word_402888
dd rva word_402898
dd rva word_4028AE
dd rva word_4028BA
dd rva word_4028C6
dd rva word_4028D2
dd rva word_4028DE
dd rva word_4028F4
dd rva word_402902
dd rva word_402914
dd rva word_402924
dd rva word_402934
dd rva word_402946
dd rva word_402954
dd rva word_402964
dd rva word_402970
dd rva word_402986
dd rva word_402998
dd rva word_4029A4
dd rva word_4029BA
dd rva word_4029CC
dd rva word_4029E0
dd rva word_4029F0
dd rva word_402A00
dd rva word_402A16
dd rva word_402A30
dd rva word_402A46
dd rva word_402A54
dd rva word_402A64
dd rva word_402A82
dd rva word_402A8E
dd rva word_402A9C
dd rva word_402AB0
dd rva word_402ABE
dd rva word_402AD0
dd rva word_402B36
dd rva word_402AF2
dd rva word_402B0C
dd rva word_402B1C
dd 0
;
; Import names for SHDOCVW.dll
;
dword_40279C dd	80000065h
dd 8000009Eh
dd 0
;
; Import names for SHLWAPI.dll
;
off_4027A8 dd rva word_402CB8
dd 800000F3h
dd 80000114h
dd 800001B5h
dd 80000178h
dd 80000050h
dd 800000B9h
dd rva word_402D18
dd rva word_402D02
dd rva word_402CF4
dd rva word_402CE0
dd rva word_402CD4
dd rva word_402CC6
dd rva word_402CA4
dd rva word_402C98
dd 800000F1h
dd 0
;
; Import names for USER32.dll
;
off_4027EC dd rva word_402C7A
dd rva word_402B80
dd rva word_402C6A
dd rva word_402C5A
dd rva word_402C3E
dd rva word_402C2E
dd rva word_402C1A
dd rva word_402C06
dd rva word_402BF8
dd rva word_402BE6
dd rva word_402BD4
dd rva word_402BC6
dd rva word_402BB4
dd rva word_402BA6
dd rva word_402B90
dd rva word_402B74
dd 0
;
; Import names for msvcrt.dll
;
off_402830 dd rva word_402838
dd 0
word_402838 dw 0EDh
db '_except_handler3',0
align 4
aMsvcrt_dll db 'msvcrt.dll',0
align 4
aAdvapi32_dll db 'ADVAPI32.dll',0
align 2
word_402866 dw 3B4h
db 'lstrlenW',0
align 2
word_402872 dw 264h
db 'MultiByteToWideChar',0
word_402888 dw 4Bh
db 'CreateEventA',0
align 4
word_402898 dw 13Eh
db 'GetCurrentThreadId',0
align 2
word_4028AE dw 3A4h
db 'lstrcatA',0
align 2
word_4028BA dw 3B3h
db 'lstrlenA',0
align 2
word_4028C6 dw 3AAh
db 'lstrcmpiA',0
word_4028D2 dw 3ADh
db 'lstrcpyA',0
align 2
word_4028DE dw 173h
db 'GetModuleFileNameA',0
align 4
word_4028F4 dw 0F0h
db 'FreeLibrary',0
word_402902 dw 197h
db 'GetProcAddress',0
align 4
word_402914 dw 241h
db 'LoadLibraryA',0
align 4
word_402924 dw 1DBh
db 'GetVersionExA',0
word_402934 dw 35Ah
db 'UnmapViewOfFile',0
word_402946 dw 31h
db 'CloseHandle',0
word_402954 dw 2B0h
db 'ReleaseMutex',0
align 4
word_402964 dw 301h
db 'SetEvent',0
align 10h
word_402970 dw 37Ah
db 'WaitForSingleObject',0
word_402986 dw 62h
db 'CreateProcessA',0
align 4
word_402998 dw 3B0h
db 'lstrcpynA',0
word_4029A4 dw 13Ch
db 'GetCurrentProcessId',0
word_4029BA dw 91h
db 'DuplicateHandle',0
word_4029CC dw 13Bh
db 'GetCurrentProcess',0
word_4029E0 dw 5Ch
db 'CreateMutexA',0
align 10h
word_4029F0 dw 257h
db 'MapViewOfFile',0
word_402A00 dw 50h
db 'CreateFileMappingA',0
align 2
word_402A16 dw 378h
db 'WaitForMultipleObjects',0
align 10h
word_402A30 dw 174h
db 'GetModuleFileNameW',0
align 2
word_402A46 dw 274h
db 'OpenProcess',0
word_402A54 dw 168h
db 'GetLastError',0
align 4
word_402A64 dw 332h
db 'SetUnhandledExceptionFilter',0
word_402A82 dw 24Bh
db 'LocalFree',0
word_402A8E dw 247h
db 'LocalAlloc',0
align 4
word_402A9C dw 175h
db 'GetModuleHandleA',0
align 10h
word_402AB0 dw 0B7h
db 'ExitThread',0
align 2
word_402ABE dw 1ACh
db 'GetStartupInfoA',0
word_402AD0 dw 300h
db 'SetErrorMode',0
align 10h
word_402AE0 dw 109h
db 'GetCommandLineA',0
word_402AF2 dw 291h
db 'QueryPerformanceCounter',0
word_402B0C dw 1D1h
db 'GetTickCount',0
align 4
word_402B1C dw 1BDh
db 'GetSystemTimeAsFileTime',0
word_402B36 dw 346h
db 'TerminateProcess',0
align 2
word_402B4A dw 357h
db 'UnhandledExceptionFilter',0
align 2
aKernel32_dll db 'KERNEL32.dll',0
align 4
word_402B74 dw 2D8h
db 'wsprintfA',0
word_402B80 dw 0FCh
db 'GetClassNameA',0
word_402B90 dw 117h
db 'GetForegroundWindow',0
word_402BA6 dw 292h
db 'ShowWindow',0
align 4
word_402BB4 dw 60h
db 'CreateWindowExA',0
word_402BC6 dw 5Dh
db 'CreateMenu',0
align 4
word_402BD4 dw 216h
db 'RegisterClassA',0
align 2
word_402BE6 dw 8Eh
db 'DefWindowProcA',0
align 4
word_402BF8 dw 1C8h
db 'LoadStringA',0
word_402C06 dw 0A1h
db 'DispatchMessageA',0
align 2
word_402C1A dw 2AAh
db 'TranslateMessage',0
align 2
word_402C2E dw 99h
db 'DestroyWindow',0
word_402C3E dw 1EAh
db 'MsgWaitForMultipleObjects',0
word_402C5A dw 1FDh
db 'PeekMessageA',0
align 2
word_402C6A dw 23Bh
db 'SendMessageA',0
align 2
word_402C7A dw 158h
db 'GetShellWindow',0
align 4
aUser32_dll db 'USER32.dll',0
align 4
word_402C98 dw 10Fh
db 'StrStrIA',0
align 4
word_402CA4 dw 30h
db 'PathFindFileNameA',0
word_402CB8 dw 0A0h
db 'SHGetValueA',0
word_402CC6 dw 136h
db 'wnsprintfA',0
align 4
word_402CD4 dw 0F0h
db 'StrCpyNW',0
align 10h
word_402CE0 dw 64h
db 'PathQuoteSpacesA',0
align 4
word_402CF4 dw 1Ch
db 'PathAppendA',0
word_402D02 dw 70h
db 'PathRemoveFileSpecA',0
word_402D18 dw 0BAh
db 'SHRegGetBoolUSValueA',0
align 10h
aShlwapi_dll db	'SHLWAPI.dll',0
aShdocvw_dll db	'SHDOCVW.dll',0
align 10h
;
; Export directory for IExplorer.EXE
;
dd 0			; Characteristics
dd 41107B80h		; TimeDateStamp: Tue Aug 03 23:00:32 2004
dw 0			; MajorVersion
dw 0			; MinorVersion
dd rva aIexplorer_exe	; Name
dd 1			; Base
dd 1			; NumberOfFunctions
dd 1			; NumberOfNames
dd rva off_402D78	; AddressOfFunctions
dd rva off_402D7C	; AddressOfNames
dd rva word_402D80	; AddressOfNameOrdinals
;
; Export Address Table for IExplorer.EXE
;
off_402D78 dd rva DllGetLCID
;
; Export Names Table for IExplorer.EXE
;
off_402D7C dd rva aDllgetlcid ;	"DllGetLCID"
;
; Export Ordinals Table	for IExplorer.EXE
;
word_402D80 dw 0
aIexplorer_exe db 'IExplorer.EXE',0
aDllgetlcid db 'DllGetLCID',0
align 80h
dd 80h dup(?)
_text ends

; Section 2. (virtual address 00003000)
; Virtual size			: 0000009C (	156.)
; Section size in file		: 00000200 (	512.)
; Offset to raw	data for section: 00002200
; Flags	C0000040: Data Readable	Writable
; Alignment	: default

; Segment type:	Pure data
; Segment permissions: Read/Write
_data segment para public 'DATA' use32
assume cs:_data
;org 403000h
dd offset sub_402460
align 8
unk_403008 db 0BDh ; Ω
db  9Fh	; ü
db  13h
db 0C5h	; ≈
db  92h	; í
db  12h
db  2Bh	; +
db  72h	; r
db  4Ah	; J
db 0BAh	; ∫
db 0B6h	; ∂
db  2Ah	; *
db 0F9h	; ˘
db 0FCh	; ¸
db  54h	; T
db  46h	; F
db  6Fh	; o
db 0A1h	; °
db 0B4h	; ¥
db 0BBh	; ª
db  43h	; C
db 0A8h	; ®
db 0FEh	; ˛
db 0F8h	; ¯
db 0A8h	; ®
db  23h	; #
db  7Dh	; }
db 0D1h	; —
db  85h	; Ö
db  84h	; Ñ
db  22h	; "
db  6Eh	; n
db 0B4h	; ¥
db  58h	; X
db    0
db  3Eh	; >
db  0Bh
db  19h
db  83h	; É
db  88h	; à
db  6Ah	; j
db  8Dh	; ç
db  64h	; d
db    2
db 0DFh	; ﬂ
db  5Fh	; _
db  65h	; e
db  7Eh	; ~
db  3Bh	; ;
db  4Dh	; M
db 0D4h	; ‘
db  10h
db  44h	; D
db 0B9h	; π
db  46h	; F
db  34h	; 4
db 0F3h	; Û
db  40h	; @
db 0F4h	; Ù
db 0BCh	; º
db  9Fh	; ü
db  4Bh	; K
db  82h	; Ç
db  1Eh
db 0CCh	; Ã
db 0A7h	; ß
db 0D0h	; –
db  2Dh	; -
db  22h	; "
db 0D7h	; ◊
db 0B1h	; ±
db 0F0h	; 
db  2Eh	; .
db 0CDh	; Õ
db  0Eh
db  21h	; !
db  52h	; R
db 0BCh	; º
db  3Eh	; >
db  81h	; Å
db 0B1h	; ±
db  1Ah
db  86h	; Ü
db  52h	; R
db  4Dh	; M
db  3Fh	; ?
db 0FBh	; ˚
db 0A2h	; ¢
db  9Dh	; ù
db 0AEh	; Æ
db 0C6h	; ∆
db  3Dh	; =
db 0AAh	; ™
db  13h
db  4Dh	; M
db  18h
db  7Ch	; |
db 0D2h	; “
db  28h	; (
db 0CEh	; Œ
db  72h	; r
db 0B1h	; ±
db  26h	; &
db  3Fh	; ?
db 0BAh	; ∫
db 0F8h	; ¯
db 0A6h	; ¶
db  4Bh	; K
db    1
db 0B9h	; π
db 0A4h	; §
db  5Ch	; \
db  43h	; C
db  68h	; h
db 0D3h	; ”
db  46h	; F
db  81h	; Å
db    0
db  7Fh	; 
db  6Ah	; j
db 0D7h	; ◊
db 0D1h	; —
db  69h	; i
db  51h	; Q
db  47h	; G
db  25h	; %
db  14h
db  40h	; @
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
dword_403090 dd	0FFFF44BFh
___security_cookie dd 0BB40h
dword_403098 dd	0
align 1000h
_data ends


end start
